FROM mysql:8.0

# Copiar el script de inicialización a la carpeta donde MySQL busca scripts
# para ejecutar durante la primera inicialización
COPY mysql-reset.sql /docker-entrypoint-initdb.d/mysql-reset.sql

# MySQL usará el plugin de autenticación nativo por defecto
CMD ["--default-authentication-plugin=mysql_native_password"]
