FROM python:3.9


WORKDIR /code

COPY ./requirements.txt /code/requirements.txt


RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
RUN pip install pydantic-settings
RUN pip install watchfiles


COPY . /code/app


CMD ["fastapi", "run", "app/main.py", "--port", "8000"]
